import { requireStateTestCoordinate } from "../../src/shared/alkisStateTestCoordinates"
import type { Prisma, Project } from "../index"
import { StateKeyEnum } from "../index"

/**
 * One seed project per Bundesland to exercise `DealAreaMap` + ALKIS WFS proxy.
 * Centers come from `src/shared/alkisStateTestCoordinates.ts` (STATE_TEST_COORDINATES).
 */
export type AlkisLandAcquisitionDemoEntry = {
  slug: string
  subTitle: string
  alkisStateKey: StateKeyEnum
  center: { lon: number; lat: number }
}

const SEED_DEMO_SPECS = [
  { slug: "rs-berlin", subTitle: "Seed: ALKIS demo Berlin", alkisStateKey: StateKeyEnum.BERLIN },
  {
    slug: "rs-baden-wuerttemberg",
    subTitle: "Seed: ALKIS demo Baden-Württemberg",
    alkisStateKey: StateKeyEnum.BADEN_WUERTTEMBERG,
  },
  { slug: "rs-hessen", subTitle: "Seed: ALKIS demo Hessen", alkisStateKey: StateKeyEnum.HESSEN },
  {
    slug: "rs-brandenburg",
    subTitle: "Seed: ALKIS demo Brandenburg",
    alkisStateKey: StateKeyEnum.BRANDENBURG,
  },
  {
    slug: "rs-nordrhein-westfalen",
    subTitle: "Seed: ALKIS demo Nordrhein-Westfalen",
    alkisStateKey: StateKeyEnum.NORDRHEIN_WESTFALEN,
  },
] as const satisfies readonly { slug: string; subTitle: string; alkisStateKey: StateKeyEnum }[]

export const ALKIS_LAND_ACQUISITION_DEMO_ENTRIES: AlkisLandAcquisitionDemoEntry[] =
  SEED_DEMO_SPECS.map((spec) => ({
    ...spec,
    center: requireStateTestCoordinate(spec.alkisStateKey),
  }))

export function alkisLandAcquisitionDemoProjects(): Omit<
  Project,
  "id" | "createdAt" | "updatedAt"
>[] {
  return ALKIS_LAND_ACQUISITION_DEMO_ENTRIES.map((d) => ({
    slug: d.slug,
    subTitle: d.subTitle,
    description: `Autogenerated seed project for ALKIS-WFS / DealAreaMap (${d.alkisStateKey}).`,
    logoSrc: null,
    partnerLogoSrcs: [],
    exportEnabled: false,
    aiEnabled: false,
    landAcquisitionModuleEnabled: true,
    showLogEntries: false,
    alkisStateKey: d.alkisStateKey,
  }))
}

/** ~350 m half-extent at mid-latitudes; line stays inside the subsection polygon. */
const DEMO_HALF_DEG = 0.004

export function buildAlkisLandAcquisitionDemoSubsection(
  projectId: number,
  center: { lon: number; lat: number },
): Prisma.SubsectionUncheckedCreateInput {
  const { lon, lat } = center
  const h = DEMO_HALF_DEG
  const ring: [number, number][] = [
    [lon - h, lat - h],
    [lon + h, lat - h],
    [lon + h, lat + h],
    [lon - h, lat + h],
    [lon - h, lat - h],
  ]
  const lineCoords: [number, number][] = [
    [lon - h * 0.45, lat],
    [lon + h * 0.45, lat],
  ]

  const lineSub: Omit<Prisma.SubsubsectionUncheckedCreateInput, "subsectionId"> = {
    slug: "alkis-demo-line",
    subTitle: "Seed line inside demo polygon",
    type: "LINE",
    geometry: {
      type: "LineString",
      coordinates: lineCoords,
    },
    labelPos: "top",
    lengthM: 250,
    width: 3,
    costEstimate: null,
    qualityLevelId: null,
    description: "Seed LINE inside subsection polygon for DealAreaMap / WFS bbox tests.",
    mapillaryKey: null,
    managerId: null,
    maxSpeed: null,
    trafficLoad: null,
    trafficLoadDate: null,
    planningCosts: null,
    deliveryCosts: null,
    constructionCosts: null,
    landAcquisitionCosts: null,
    expensesOfficialOrders: null,
    expensesTechnicalVerification: null,
    nonEligibleExpenses: null,
    revenuesEconomicIncome: null,
    contributionsThirdParties: null,
    grantsOtherFunding: null,
    ownFunds: null,
  }

  return {
    projectId,
    operatorId: null,
    slug: "alkis-demo",
    order: 1,
    type: "POLYGON",
    description:
      "Seed subsection (polygon) for ALKIS land-acquisition demos; line subsubsection lies inside.",
    labelPos: "top",
    geometry: {
      type: "Polygon",
      coordinates: [ring],
    },
    lengthM: null,
    managerId: null,
    subsubsections: { create: [lineSub] },
  }
}
