-- CreateEnum
CREATE TYPE "StateKeyEnum" AS ENUM ('BADEN_WUERTTEMBERG', 'BAYERN', 'BERLIN', 'BRANDENBURG', 'BREMEN', 'HAMBURG', 'HESSEN', 'MECKLENBURG_VORPOMMERN', 'NIEDERSACHSEN', 'NORDRHEIN_WESTFALEN', 'RHEINLAND_PFALZ', 'SAARLAND', 'SACHSEN', 'SACHSEN_ANHALT', 'SCHLESWIG_HOLSTEIN', 'THUERINGEN', 'DISABLED');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "alkisStateKey" "StateKeyEnum" NOT NULL DEFAULT 'DISABLED';
