import { defineConfig } from "oxlint"
import reactHooksJs from "oxlint-config-react-hooks-js/configs/recommended-latest.json" with { type: "json" }

export default defineConfig({
  plugins: ["eslint", "typescript", "unicorn", "oxc", "react"],
  options: { typeAware: true },
  ignorePatterns: [
    // Agent skills/reference docs — not application source
    ".agents/**",
    // TanStack Router codegen (generated by Vite plugin)
    "src/routeTree.gen.ts",
    // Vite/Nitro production build output
    ".output/**",
    // Playwright HTML report from `test-e2e` (gitignored)
    "playwright-report/**",
  ],
  rules: {
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/no-floating-promises": "off",
    "typescript/no-duplicate-type-constituents": "off",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/restrict-template-expressions": "off",
    "typescript/no-base-to-string": "off",
    "typescript/await-thenable": "off",
    "typescript/unbound-method": "off",
    "typescript/no-meaningless-void-operator": "off",
    "typescript/no-useless-default-assignment": "off",
    "typescript/no-misused-spread": "off",
    "typescript/require-array-sort-compare": "off",
    "typescript/no-array-delete": "off",
  },
  overrides: [
    {
      files: ["tests/**"],
      rules: {
        "react/rules-of-hooks": "off",
      },
    },
    {
      files: ["**/*.test.ts", "**/*.test.tsx"],
      rules: {
        "typescript/no-non-null-assertion": "off",
      },
    },
    // Trassenscout custom rules — one oxlint jsPlugin per rule (lint/plugins/)
    {
      files: ["src/**/*.{ts,tsx}"],
      jsPlugins: [
        { name: "trassenscout-no-use-client", specifier: "./lint/plugins/no-use-client.mjs" },
      ],
      rules: {
        "trassenscout-no-use-client/no-use-client": "error",
      },
    },
    {
      files: ["src/**/*.{ts,tsx}"],
      excludeFiles: ["**/*.test.ts", "**/*.test.tsx"],
      jsPlugins: [
        { name: "trassenscout-no-re-export", specifier: "./lint/plugins/no-re-export.mjs" },
      ],
      rules: {
        "trassenscout-no-re-export/no-re-export": "error",
      },
    },
    {
      files: ["src/server/**/*.functions.ts"],
      jsPlugins: [
        {
          name: "trassenscout-no-dynamic-server-import",
          specifier: "./lint/plugins/no-dynamic-server-import.mjs",
        },
      ],
      rules: {
        "trassenscout-no-dynamic-server-import/no-dynamic-server-import": "error",
      },
    },
    {
      files: ["src/**/*.{ts,tsx}"],
      excludeFiles: ["src/server/auth/**", "**/*.test.ts", "**/*.test.tsx"],
      jsPlugins: [
        {
          name: "trassenscout-no-auth-boundary-import",
          specifier: "./lint/plugins/no-auth-boundary-import.mjs",
        },
      ],
      rules: {
        "trassenscout-no-auth-boundary-import/no-auth-boundary-import": "error",
      },
    },
    {
      files: ["src/routes/api/**/*.ts", "src/routes/**/*.{ts,tsx}", "src/server/**/*.server.ts"],
      excludeFiles: [
        "src/server/auth/**",
        "**/db.server.ts",
        "**/paginate.server.ts",
        "**/_utils/**",
        "**/observability/**",
        "**/*.test.ts",
        "**/*.test.tsx",
      ],
      jsPlugins: [
        {
          name: "trassenscout-require-endpoint-auth",
          specifier: "./lint/plugins/require-endpoint-auth.mjs",
        },
      ],
      rules: {
        "trassenscout-require-endpoint-auth/require-endpoint-auth": "error",
      },
    },
    {
      files: ["**/*.tsx"],
      jsPlugins: [
        { name: "react-compiler-js", specifier: "eslint-plugin-react-compiler" },
        { name: "react-hooks-js", specifier: "eslint-plugin-react-hooks" },
      ],
      rules: {
        ...reactHooksJs.rules,
        "react-compiler-js/react-compiler": "error",
      },
    },
    {
      files: ["src/components/**", "src/routes/**"],
      excludeFiles: ["**/*.server.ts", "**/*.functions.ts", "src/routes/api/**"],
      jsPlugins: [{ name: "compat", specifier: "eslint-plugin-compat" }],
      rules: {
        "compat/compat": "error",
      },
    },
  ],
})
