import { ProtocolTypePill } from "@/src/app/(loggedInProjects)/[projectSlug]/protocols/_components/ProtocolsTable"
import { getFullname } from "@/src/pagesComponents/users/utils/getFullname"
import getProtocol from "@/src/server/protocols/queries/getProtocol"
import getProtocols from "@/src/server/protocols/queries/getProtocols"
import { ProtocolReviewState, ProtocolType } from "@prisma/client"

export const CreateEditReviewHistory = ({
  protocol,
  className,
}: {
  protocol: Awaited<ReturnType<typeof getProtocols>>[0] | Awaited<ReturnType<typeof getProtocol>>
  className?: string
}) => {
  return (
    <div
      className={`flex flex-shrink-0 flex-col gap-1 rounded-lg border border-gray-300 p-2 ${className || ""}`}
    >
      <p className="text-xs">
        <span>Erstellt von </span>
        <ProtocolTypePill type={protocol.protocolAuthorType} author={protocol.author} />
      </p>
      <p className="mt-2 text-xs">
        <span>Zuletzt bearbeitet von </span>
        <ProtocolTypePill type={protocol.protocolUpdatedByType} author={protocol.updatedBy} />
      </p>
      {/* if this protocol is generated by the system show reviewer */}
      {protocol.protocolAuthorType === ProtocolType.SYSTEM &&
        protocol.reviewState === ProtocolReviewState.APPROVED &&
        protocol.reviewedBy && (
          <p className="mt-2 text-xs">
            <span>Freigabe durch </span>
            <span>{getFullname(protocol.reviewedBy)}</span>
          </p>
        )}
    </div>
  )
}
