import { ProjectRecordTypePill } from "@/src/app/(loggedInProjects)/[projectSlug]/project-records/_components/ProjectRecordTable"
import { getFullname } from "@/src/pagesComponents/users/utils/getFullname"
import getProjectRecord from "@/src/server/projectRecord/queries/getProjectRecord"
import getProjectRecords from "@/src/server/projectRecord/queries/getProjectRecords"
import { ProjectRecordReviewState, ProjectRecordType } from "@prisma/client"

export const CreateEditReviewHistory = ({
  projectRecord,
  className,
}: {
  projectRecord:
    | Awaited<ReturnType<typeof getProjectRecords>>[0]
    | Awaited<ReturnType<typeof getProjectRecord>>
  className?: string
}) => {
  return (
    <div
      className={`flex flex-shrink-0 flex-col gap-1 rounded-lg border border-gray-300 p-2 ${className || ""}`}
    >
      <p className="text-xs">
        <span>Erstellt von </span>
        <ProjectRecordTypePill
          type={projectRecord.projectRecordAuthorType}
          author={projectRecord.author}
        />
      </p>
      <p className="mt-2 text-xs">
        <span>Zuletzt bearbeitet von </span>
        <ProjectRecordTypePill
          type={projectRecord.projectRecordUpdatedByType}
          author={projectRecord.updatedBy}
        />
      </p>
      {/* if this projectRecord is generated by the system show reviewer */}
      {projectRecord.projectRecordAuthorType === ProjectRecordType.SYSTEM &&
        projectRecord.reviewState === ProjectRecordReviewState.APPROVED &&
        projectRecord.reviewedBy && (
          <p className="mt-2 text-xs">
            <span>Freigabe durch </span>
            <span>{getFullname(projectRecord.reviewedBy)}</span>
          </p>
        )}
    </div>
  )
}
