/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Survey {
  id: number
  title: TranslatableText
  version: 1
  createdAt: string
  faviconUrl: string
  pages: Page[]
}

export interface Page {
  id: number
  title: TranslatableText
  description: TranslatableText
  questions?: Question[]
  buttons: Button[]
}
export interface Question {
  id: number
  component: "singleResponse" | "multipleResponse" | "text"
  label: TranslatableText
  "//* props.oneOf is here for generating typescript"?: "*//"
  props: SingleOrMultiResponseProps | TextResponseProps
}

export interface Button {
  label: TranslatableText
  color: "white" | "pink"
  onClick: {
    action: "nextPage" | "previousPage" | "submit"
    arguments?: unknown[]
  }
}
export interface TranslatableText {
  de: string
}
export interface SingleOrMultiResponseProps {
  responses: Response[]
}
export interface Response {
  id: number
  text: TranslatableText
  help?: TranslatableText
}
export interface TextResponseProps {}
