import { ProjectRecordReviewStatePill } from "@/src/app/(admin)/admin/project-records/_components/AdminProjectRecordTable"
import { ProjectRecordTypePill } from "@/src/app/(loggedInProjects)/[projectSlug]/project-records/_components/ProjectRecordTypePill"
import { SuperAdminBox } from "@/src/core/components/AdminBox/SuperAdminBox"
import { isAdmin } from "@/src/pagesComponents/users/utils/isAdmin"
import getProjectRecord from "@/src/server/projectRecords/queries/getProjectRecord"
import getProjectRecordAdmin from "@/src/server/projectRecords/queries/getProjectRecordAdmin"
import getProjectRecords from "@/src/server/projectRecords/queries/getProjectRecords"
import { useCurrentUser } from "@/src/server/users/hooks/useCurrentUser"
import { ProjectRecordReviewState, ProjectRecordType } from "@prisma/client"

const CreateEditReviewHistoryComponent = ({
  projectRecord,
}: {
  projectRecord:
    | Awaited<ReturnType<typeof getProjectRecordAdmin>>
    | Awaited<ReturnType<typeof getProjectRecords>>[0]
    | Awaited<ReturnType<typeof getProjectRecord>>
}) => (
  <div className="my-8 inline-flex shrink-0 flex-col gap-1 rounded-lg border border-gray-300 p-2 py-2.5">
    <p className="text-xs">
      <span>Erstellt von </span>
      <ProjectRecordTypePill
        type={projectRecord.projectRecordAuthorType}
        author={projectRecord.author}
      />
    </p>
    <p className="mt-2 text-xs">
      <span>Zuletzt bearbeitet von </span>
      <ProjectRecordTypePill
        type={projectRecord.projectRecordUpdatedByType}
        author={projectRecord.updatedBy}
      />
    </p>
    {/* if this projectRecord is generated by the system show reviewe state*/}
    {projectRecord.projectRecordAuthorType === ProjectRecordType.SYSTEM && (
      <p className="mt-2 text-xs">
        <span> Bestätigung-Status </span>
        <ProjectRecordReviewStatePill state={projectRecord.reviewState} />
      </p>
    )}
    {/* if this projectRecord is generated by the system show reviewer */}
    {projectRecord.projectRecordAuthorType === ProjectRecordType.SYSTEM &&
      projectRecord.reviewState === ProjectRecordReviewState.APPROVED &&
      projectRecord.reviewedBy && (
        <p className="mt-2 text-xs">
          <span> Bestätigung durch </span>
          <ProjectRecordTypePill type="USER" author={projectRecord.reviewedBy} />
        </p>
      )}
    {projectRecord.projectRecordAuthorType === ProjectRecordType.SYSTEM &&
      projectRecord.reviewNotes && (
        <p className="mt-2 text-xs">
          <span>Freigebe-Notiz: </span>
          <span>{projectRecord.reviewNotes}</span>
        </p>
      )}
  </div>
)

export const CreateEditReviewHistory = ({
  projectRecord,
}: {
  projectRecord:
    | Awaited<ReturnType<typeof getProjectRecordAdmin>>
    | Awaited<ReturnType<typeof getProjectRecords>>[0]
    | Awaited<ReturnType<typeof getProjectRecord>>
}) => {
  const user = useCurrentUser()
  const isUserAdmin = isAdmin(user)
  const aiEnabled = projectRecord.project.aiEnabled

  if (!aiEnabled && !isUserAdmin) return null

  if (aiEnabled) return <CreateEditReviewHistoryComponent projectRecord={projectRecord} />

  // Admins always see the create edit review details
  return (
    <SuperAdminBox>
      <CreateEditReviewHistoryComponent projectRecord={projectRecord} />
    </SuperAdminBox>
  )
}
