ALTER TABLE "Section"
  ADD COLUMN "end"   TEXT NOT NULL DEFAULT 'end',
  ADD COLUMN "start" TEXT NOT NULL DEFAULT 'start';

ALTER TABLE "Section"
  ALTER COLUMN "end"   DROP DEFAULT,
  ALTER COLUMN "start" DROP DEFAULT;

ALTER TABLE "Subsection"
  ADD COLUMN "end"   TEXT NOT NULL DEFAULT 'end',
  ADD COLUMN "start" TEXT NOT NULL DEFAULT 'start';

ALTER TABLE "Subsection"
  ALTER COLUMN "end"   DROP DEFAULT,
  ALTER COLUMN "start" DROP DEFAULT;
