export const subsubsectionFieldTranslations = {
  subsectionId: "Planungsabschnitt ID",
  slug: "Kürzel",
  description: "Beschreibung",
  type: "Typ der Geometrie",
  geometry: "Geometrie",
  isExistingInfra: "Bestand – keine Maßnahme geplant",
  subsubsectionTaskId: "Maßnahmentyp",
  location: "Lage",
  lengthM: "Länge",
  width: "Breite",
  costEstimate: "Kostenschätzung",
  qualityLevelId: "Ausbaustandard",
  subsubsectionInfraId: "Führungsform",
  subsubsectionStatusId: "Phase",
  subsubsectionInfrastructureTypeIds: "Gegenstände der Förderung",
  estimatedConstructionDateString: "Angestrebtes Baujahr",
  mapillaryKey: "Mapillary Bild Referenz",
  managerId: "Projektleiter:in",
  labelPos: "Anzeige-Optionen für Karten-Label",
  maxSpeed: "Zulässige Höchstgeschwindigkeit an der Straße",
  trafficLoad: "Verkehrsbelastung an Werktagen an dieser Straße (Kfz/24h)",
  trafficLoadDate: "Verkehrsbelastung ermittelt am (Datum)",
  planningCosts: "Planungskosten",
  constructionCosts: "Baukosten",
  deliveryCosts: "Lieferkosten",
  landAcquisitionCosts: "Grunderwerbskosten",
  expensesOfficialOrders: "Ausgaben aufgrund behördlicher Anordnungen",
  expensesTechnicalVerification: "Ausgaben für den fachtechnischen Nachweis usw.",
  nonEligibleExpenses: "Nicht zuwendungsfähige Ausgaben",
  grantAmount: "Zuwendung",
  ownFunds: "Einsatz Eigenmittel",
  grantsOtherFunding: "Zuwendungen aus anderen Förderprogrammen",
  revenuesEconomicIncome: "Erlöse und wirtschaftliche Einnahmen",
  contributionsThirdParties: "Beiträge Dritter",
  remainingFunding: "Noch verfügbare Fördermittel",
  disbursedFunding: "Ausgezahlte Fördermittel",
  planningPeriod: "Planungszeit (in Monaten)",
  constructionPeriod: "Bauzeit (in Monaten)",
  estimatedCompletionDate: "Datum geplante Fertigstellung",
  subTitle: "Untertitel",
  specialFeatures: "Besonderheiten",
  widthExisting: "Breite Bestand",
} as const

export const fieldDataTypes = {
  slug: "String",
  description: "String",
  subTitle: "String",
  geometry: "Point | Linestring",
  isExistingInfra: "Boolean",
  subsubsectionTaskId: "Relation (Number)",
  location: "Enum (LocationEnum)",
  lengthM: "Number",
  width: "Number",
  widthExisting: "Number",
  costEstimate: "Number",
  qualityLevelId: "Relation (Number)",
  subsubsectionInfraId: "Relation (Number)",
  subsubsectionStatusId: "Relation (Number)",
  subsubsectionInfrastructureTypeIds: "Relation (Array)",
  estimatedConstructionDateString: "String",
  mapillaryKey: "String",
  managerId: "Relation (Number)",
  labelPos: "Enum (LabelPositionEnum)",
  maxSpeed: "Number",
  trafficLoad: "Number",
  trafficLoadDate: "Date",
  planningCosts: "Number",
  constructionCosts: "Number",
  deliveryCosts: "Number",
  landAcquisitionCosts: "Number",
  expensesOfficialOrders: "Number",
  expensesTechnicalVerification: "Number",
  nonEligibleExpenses: "Number",
  grantAmount: "Number",
  ownFunds: "Number",
  grantsOtherFunding: "Number",
  revenuesEconomicIncome: "Number",
  contributionsThirdParties: "Number",
  remainingFunding: "Number",
  disbursedFunding: "Number",
  planningPeriod: "Number",
  constructionPeriod: "Number",
  estimatedCompletionDate: "Date",
  subsectionId: "Relation (Number)",
  specialFeatures: "Relation (Array)",
  type: "Enum (GeometryTypeEnum)",
} as const

export const requiredFields = [
  "slug",
  "type",
  "geometry",
  "labelPos",
  "isExistingInfra",
  "subsectionId",
] as const
