name: Run daily tasks

on:
  workflow_dispatch:
  schedule:
    # Runs day at 5:00 AM
    - cron: "0 5 * * *"

permissions:
  contents: read

jobs:
  run-daily-tasks-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Cleanup invites STAGING
        # --fail makes the github action fail on error
        # -s (silent) removes the progress bar
        # -S (show error) makes sure errors show even with -s active
        run: |
          curl --fail -s -S \
            -H "Authorization: Bearer ${{ secrets.TS_API_KEY }}" \
            -X GET "https://staging.trassenscout.de/api/cron-invites-cleanup"
      - name: Cleanup logEntries STAGING
        run: |
          curl --fail -s -S \
            -H "Authorization: Bearer ${{ secrets.TS_API_KEY }}" \
            -X GET "https://staging.trassenscout.de/api/cron-logEntries-cleanup"
      - name: Cleanup created surveyResponses STAGING
        run: |
          curl --fail -s -S \
            -H "Authorization: Bearer ${{ secrets.TS_API_KEY }}" \
            -X GET "https://staging.trassenscout.de/api/cron-surveyResponses-cleanup"

  run-daily-tasks-production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Cleanup invites PRODUCTION
        run: |
          curl --fail -s -S \
            -H "Authorization: Bearer ${{ secrets.TS_API_KEY }}" \
            -X GET "https://trassenscout.de/api/cron-invites-cleanup"
      - name: Cleanup logEntries PRODUCTION
        run: |
          curl --fail -s -S \
            -H "Authorization: Bearer ${{ secrets.TS_API_KEY }}" \
            -X GET "https://trassenscout.de/api/cron-logEntries-cleanup"
      - name: Cleanup created surveyResponses PRODUCTION
        run: |
          curl --fail -s -S \
            -H "Authorization: Bearer ${{ secrets.TS_API_KEY }}" \
            -X GET "https://trassenscout.de/api/cron-surveyResponses-cleanup"
