name: Run daily tasks

on:
  workflow_dispatch:
  schedule:
    # Runs day at 5:00 AM
    - cron: "0 5 * * *"

jobs:
  run-daily-tasks-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup invites STAGING
        run: curl --fail -X GET "https://staging.trassenscout.de/api/private/cron-invites-cleanup?apiKey=${{ secrets.TS_API_KEY }}"
      - name: Cleanup logEntries STAGING
        run: curl --fail -X GET "https://staging.trassenscout.de/api/private/cron-logEntries-cleanup?apiKey=${{ secrets.TS_API_KEY }}"
      - name: Cleanup invites PRODUCTION
        run: curl --fail -X GET "https://trassenscout.de/api/private/cron-invites-cleanup?apiKey=${{ secrets.TS_API_KEY }}"
      - name: Cleanup logEntries PRODUCTION
        run: curl --fail -X GET "https://trassenscout.de/api/private/cron-logEntries-cleanup?apiKey=${{ secrets.TS_API_KEY }}"
