name: Deploy Production
on:
  push:
    branches:
      - main

jobs:
  setup_env:
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit
    with:
      ENVIRONMENT: production

  deploy-app:
    needs: setup_env
    uses: ./.github/workflows/deploy-app.yml
    secrets: inherit
    with:
      ENVIRONMENT: production

  services:
    needs: deploy-app
    uses: ./.github/workflows/services.yml
    secrets: inherit
    with:
      ENVIRONMENT: production
