name: Deploy App to Ionos
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      NEXT_PUBLIC_APP_ORIGIN:
        required: true
        type: string
      NEXT_PUBLIC_APP_ENV:
        required: true
        type: string
      APP_ORIGIN:
        required: true
        type: string
      # CONFIG_CHANGED:
      #   required: true
      #   type: boolean
    secrets:
      ASSETS_BUCKET_HOST:
        required: true
      ASSETS_BUCKET_PATH:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true

jobs:
  diff_app:
    uses: ./.github/workflows/diff-last-run.yml
    with:
      CHECK_DIFF_LOCATIONS: src/ db/ public/ emails/ docker/
  build_app:
    runs-on: ubuntu-latest
    needs: diff_app
    if: ${{ needs.diff_app.outputs.changes == 'true' }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upgrade AWS CLI version and setup lightsailctl
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/app/Dockerfile
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            public.ecr.aws/n0p8j4k5/trassenscout/app:${{ github.sha }}
            public.ecr.aws/n0p8j4k5/trassenscout/app:${{ inputs.ENVIRONMENT }}-latest
          build-args: |
            NEXT_PUBLIC_APP_ENV=${{ inputs.NEXT_PUBLIC_APP_ENV }}
            NEXT_PUBLIC_APP_ORIGIN=${{ inputs.NEXT_PUBLIC_APP_ORIGIN }}

      - name: Push app image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n0p8j4k5/
          docker push --all-tags public.ecr.aws/n0p8j4k5/trassenscout/app

  restart_app:
    runs-on: ubuntu-latest
    needs: [diff_app, build_app]
    if: ${{ needs.diff_app.outputs.changes == 'true' || inputs.CONFIG_CHANGED && always() }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ inputs.APP_ORIGIN }}
    steps:
      - name: Stop & Start container on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /srv/trassenscout-${{ inputs.ENVIRONMENT }}
            rm docker-compose.yml
            mv docker-compose.server.yml docker-compose.yml
            echo "Pulling latest 'app' image"
            docker compose pull app
            echo "Restarting 'app' container"
            docker compose up app -d
            echo "Pruning images"
            docker image prune -fa
