name: Restart Services

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  # diff_docker:
  #   uses: ./.github/workflows/diff-last-run.yml
  #   with:
  #     CHECK_DIFF_LOCATIONS: docker-compose*

  restart_services:
    runs-on: ubuntu-latest
    # needs: diff_docker
    # if: ${{ needs.diff_docker.outputs.changes == 'true' }}
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      # `url` adds adds link to the Github UI
      url: ${{ vars.APP_ORIGIN }}
    steps:
      - name: Stop & Start containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /srv/trassenscout-${{ inputs.ENVIRONMENT }}
            echo "Pull all containers"
            docker compose pull
            echo "Restart all containers"
            docker compose up -d
            echo "Docker prune images"
            docker image prune -fa
