name: Services

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  pull_restart:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      # `url` adds adds link to the Github UI
      url: ${{ vars.APP_ORIGIN }}
    steps:
      - name: "AWS: Configure credentials"
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Get ECR login password
        id: ecr-login
        run: |
          ECR_PASSWORD=$(aws ecr get-login-password --region eu-central-1)
          echo "::add-mask::$ECR_PASSWORD"
          echo "password=$ECR_PASSWORD" >> $GITHUB_OUTPUT

      - name: Pull, Restart, Cleanup
        uses: appleboy/ssh-action@v1
        env:
          ECR_PASSWORD: ${{ steps.ecr-login.outputs.password }}
          ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: ECR_PASSWORD,ECR_REGISTRY
          script: |
            set -e
            echo "$ECR_PASSWORD" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
            cd /srv/trassenscout-${{ inputs.ENVIRONMENT }}
            echo "Pull all containers"
            docker compose pull
            echo "Restart all containers"
            docker compose up -d
            echo "Docker prune images"
            docker image prune -fa
